In [1]:
print("Hello World")

Hello World


# Python Packages for Analytics, ML

- numpy, scipy, statsmodels: mathematical computation, scientifc computations, statistical analysis
- pandas: data import export, data cleaning, aggregation, transformation, visualization
- matplotlib,seaborn, plotly : Data visualization

- scikit-learn: Machine Learning Algorithms, FEature Engineering

- tensorflow, pytorch : Deep Learning implementation

- openCV, imgaug : Computer vision
- nltk, textblob, gensim, spacy: text processing, natural language processing
- mlflow: MLOps
- flask, fastapi, django: web services, REST API
  

## WOrking with numpy

In [2]:
x = [3,5,6]
y = [6,7,3]

print(x+y)

[3, 5, 6, 6, 7, 3]


In [3]:
import numpy as np

In [5]:
x = np.array([3,5,6])
y = np.array([5,7,2])

print(x+y)

[ 8 12  8]


In [6]:
print(x-y)

[-2 -2  4]


In [7]:
x = np.array([[4,5,6],[6,4,2],[9,3,6]])
x

array([[4, 5, 6],
       [6, 4, 2],
       [9, 3, 6]])

In [8]:
type(x)

numpy.ndarray

In [9]:
x.min()

2

In [10]:
x.max()

9

In [11]:
x.sum()

45

# Arrays with numpy

In [ ]:
x = np.ones((3,4))
x

In [ ]:
x = np.zeros((3,4))
x

In [ ]:
x = np.linspace(2,20,12)
x

In [ ]:
x = np.arange(2,20,2.5)
x

In [ ]:
x = np.random.rand(5)
x

In [ ]:
x = np.random.randn(5)
x

In [ ]:
x = np.random.randint(3,20,5)
x

In [21]:
x = np.random.randint(3,20,5)
x

array([ 8,  9, 10,  4,  7])

In [22]:
np.random.seed(30)
x = np.random.randint(3,20,5)
x

array([ 8,  8, 16, 16, 15])

In [23]:
np.random.seed(30)
x = np.random.randint(3,20,5)
x

array([ 8,  8, 16, 16, 15])

## Linear Algebra with numpy

In [24]:
x = np.array([[4,5,6],[6,4,2],[9,3,6]])
x

array([[4, 5, 6],
       [6, 4, 2],
       [9, 3, 6]])

In [26]:
np.linalg.det(x)

-126.00000000000011

In [27]:
np.linalg.inv(x)

array([[-0.14285714,  0.0952381 ,  0.11111111],
       [ 0.14285714,  0.23809524, -0.22222222],
       [ 0.14285714, -0.26190476,  0.11111111]])

5x - 3y = 16

3x + y = 18

In [28]:
coef = [[5,-3],[3,1]]
cons = [16,18]

np.linalg.solve(coef,cons)

array([5., 3.])